service: ${env:API_NAME}-rel-con-col-res

custom:
  dotenv:
    path: ../../../.env

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-bundle

provider:
  name: aws
  region: ${env:REGION}
  runtime: nodejs12.x

  stage: ${env:NODE_ENV}
  versionFunctions: false
  vpc:
    securityGroupIds:
      - ${env:SECURITY_GROUP_ID}
    subnetIds:
      - ${env:SUBNET1_ID}
      - ${env:SUBNET2_ID}

package:
  individually: true

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: relations/containers/collection/resource
          method: post
          cors: true
    environment:
      TABLE_NAME: "CollectionResourceRelation"
  getOne:
    handler: handler.getOne
    events:
      - http:
          path: relations/containers/collection/{id1}/resource/{id2}
          method: get
          cors: true
    environment:
      TABLE_NAME: "CollectionResourceRelation"
      FK_NAME_1: "CollectionId"
      FK_NAME_2: "ResourceId"
  getAll:
    handler: handler.getAll
    events:
      - http:
          path: relations/containers/collection/resource
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                CollectionId: false
                offset: false
                limit: false
    environment:
      TABLE_NAME: "CollectionResourceRelation"
      FK_NAME_1: "CollectionId"
      FK_NAME_2: "ResourceId"
  update:
    handler: handler.update
    events:
      - http:
          path: relations/containers/collection/{id1}/resource/{id2}
          method: patch
          cors: true
    environment:
      TABLE_NAME: "CollectionResourceRelation"
      FK_NAME_1: "CollectionId"
      FK_NAME_2: "ResourceId"
  destroy:
    handler: handler.destroy
    events:
      - http:
          path: relations/containers/collection/{id1}/resource/{id2}
          method: delete
          cors: true
    environment:
      TABLE_NAME: "CollectionResourceRelation"
      FK_NAME_1: "CollectionId"
      FK_NAME_2: "ResourceId"
