service: ${env:API_NAME}-the

custom:
  dotenv:
    path: ../../.env

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-bundle

provider:
  name: aws
  region: ${env:REGION}
  runtime: nodejs12.x

  stage: ${env:NODE_ENV}
  versionFunctions: false
  vpc:
    securityGroupIds:
      - ${env:SECURITY_GROUP_ID}
    subnetIds:
      - ${env:SUBNET1_ID}
      - ${env:SUBNET2_ID}

package:
  individually: true

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: themes
          method: post
          cors: true
  getOne:
    handler: handler.getOne
    events:
      - http:
          path: themes/{id}
          method: get
          cors: true
  getAll:
    handler: handler.getAll
    events:
      - http:
          path: themes
          method: get
          cors: true
  update:
    handler: handler.update
    events:
      - http:
          path: themes/{id}
          method: patch
          cors: true
  destroy:
    handler: handler.destroy
    events:
      - http:
          path: themes/{id}
          method: delete
          cors: true
