service: ${env:API_NAME}-use

custom:
  dotenv:
    path: ../../.env

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  region: ${env:REGION}
  runtime: nodejs12.x
  timeout: 30
  stage: ${env:NODE_ENV}
  versionFunctions: false
  vpc:
    securityGroupIds:
      - ${env:SECURITY_GROUP_ID}
    subnetIds:
      - ${env:SUBNET1_ID}
      - ${env:SUBNET2_ID}

package:
  individually: true

functions:
  userCreate:
    handler: handler.userCreate
    events:
      - http:
          path: users
          method: post
          cors: true
  userGetOne:
    handler: handler.userGetOne
    events:
      - http:
          path: users/{id}
          method: get
          cors: true
  userGetAll:
    handler: handler.userGetAll
    events:
      - http:
          path: users
          method: get
          cors: true
  userUpdate:
    handler: handler.userUpdate
    events:
      - http:
          path: users/{id}
          method: patch
          cors: true
  userDestroy:
    handler: handler.userDestroy
    events:
      - http:
          path: users/{id}
          method: delete
          cors: true
