service: ${env:API_NAME}-own-rel-use-col

custom:
  dotenv:
    path: ../../../.env

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  region: ${env:REGION}
  runtime: nodejs12.x
  timeout: 30
  stage: ${env:NODE_ENV}
  versionFunctions: false
  vpc:
    securityGroupIds:
      - ${env:SECURITY_GROUP_ID}
    subnetIds:
      - ${env:SUBNET1_ID}
      - ${env:SUBNET2_ID}

package:
  individually: true

functions:
  # userCollection
  userCollectionOwnershipRelationCreate:
    handler: ../handler.ownershipRelationCreate
    events:
      - http:
          path: userCollectionOwnershipRelations
          method: post
          cors: true
    environment:
      TABLE_NAME: "UserCollectionOwnershipRelation"
  userCollectionOwnershipRelationGetOne:
    handler: ../handler.ownershipRelationGetOne
    events:
      - http:
          path: userCollectionOwnershipRelations/{id1}/{id2}
          method: get
          cors: true
    environment:
      TABLE_NAME: "UserCollectionOwnershipRelation"
      FK_NAME_1: "UserId"
      FK_NAME_2: "CollectionId"
  userCollectionOwnershipRelationGetAll:
    handler: ../handler.ownershipRelationGetAll
    events:
      - http:
          path: userCollectionOwnershipRelations
          method: get
          cors: true
    environment:
      TABLE_NAME: "UserCollectionOwnershipRelation"
  userCollectionOwnershipRelationUpdate:
    handler: ../handler.ownershipRelationUpdate
    events:
      - http:
          path: userCollectionOwnershipRelations/{id1}/{id2}
          method: put
          cors: true
    environment:
      TABLE_NAME: "UserCollectionOwnershipRelation"
      FK_NAME_1: "UserId"
      FK_NAME_2: "CollectionId"
  userCollectionOwnershipRelationDestroy:
    handler: ../handler.ownershipRelationDestroy
    events:
      - http:
          path: userCollectionOwnershipRelations/{id1}/{id2}
          method: delete
          cors: true
    environment:
      TABLE_NAME: "UserCollectionOwnershipRelation"
      FK_NAME_1: "UserId"
      FK_NAME_2: "CollectionId"
