service: ${env:API_NAME}-rel-con-col-col

custom:
  dotenv:
    path: ../../../.env

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-bundle

provider:
  name: aws
  region: ${env:REGION}
  runtime: nodejs12.x
  timeout: 30
  stage: ${env:NODE_ENV}
  versionFunctions: false
  vpc:
    securityGroupIds:
      - ${env:SECURITY_GROUP_ID}
    subnetIds:
      - ${env:SUBNET1_ID}
      - ${env:SUBNET2_ID}

package:
  individually: true

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: relations/containers/collection/collection
          method: post
          cors: true
    environment:
      TABLE_NAME: "CollectionCollectionRelation"
  getOne:
    handler: handler.getOne
    events:
      - http:
          path: relations/containers/collection/{id1}/collection/{id2}
          method: get
          cors: true
    environment:
      TABLE_NAME: "CollectionCollectionRelation"
      FK_NAME_1: "ParentId"
      FK_NAME_2: "ChildId"
  getAll:
    handler: handler.getAll
    events:
      - http:
          path: relations/containers/collection/collection
          method: get
          cors: true
    environment:
      TABLE_NAME: "CollectionCollectionRelation"
  update:
    handler: handler.update
    events:
      - http:
          path: relations/containers/collection/{id1}/collection/{id2}
          method: patch
          cors: true
    environment:
      TABLE_NAME: "CollectionCollectionRelation"
      FK_NAME_1: "ParentId"
      FK_NAME_2: "ChildId"
  destroy:
    handler: handler.destroy
    events:
      - http:
          path: relations/containers/collection/{id1}/collection/{id2}
          method: delete
          cors: true
    environment:
      TABLE_NAME: "CollectionCollectionRelation"
      FK_NAME_1: "ParentId"
      FK_NAME_2: "ChildId"
