service: ${env:API_NAME}-rel-own-use-com

custom:
  dotenv:
    path: ../../../.env

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-bundle

provider:
  name: aws
  region: ${env:REGION}
  runtime: nodejs12.x
  timeout: 30
  stage: ${env:NODE_ENV}
  versionFunctions: false
  vpc:
    securityGroupIds:
      - ${env:SECURITY_GROUP_ID}
    subnetIds:
      - ${env:SUBNET1_ID}
      - ${env:SUBNET2_ID}

package:
  individually: true

functions:
  create:
    handler: ../handler.ownershipRelationCreate
    events:
      - http:
          path: relations/ownerships/user/community
          method: post
          cors: true
    environment:
      TABLE_NAME: "UserCommunityOwnershipRelation"
  getOne:
    handler: ../handler.ownershipRelationGetOne
    events:
      - http:
          path: relations/ownerships/user/{id1}/community/{id2}
          method: get
          cors: true
    environment:
      TABLE_NAME: "UserCommunityOwnershipRelation"
      FK_NAME_1: "UserId"
      FK_NAME_2: "CommunityId"
  getAll:
    handler: ../handler.ownershipRelationGetAll
    events:
      - http:
          path: relations/ownerships/user/community
          method: get
          cors: true
    environment:
      TABLE_NAME: "UserCommunityOwnershipRelation"
  update:
    handler: ../handler.ownershipRelationUpdate
    events:
      - http:
          path: relations/ownerships/user/{id1}/community/{id2}
          method: patch
          cors: true
    environment:
      TABLE_NAME: "UserCommunityOwnershipRelation"
      FK_NAME_1: "UserId"
      FK_NAME_2: "CommunityId"
  destroy:
    handler: ../handler.ownershipRelationDestroy
    events:
      - http:
          path: relations/ownerships/user/{id1}/community/{id2}
          method: delete
          cors: true
    environment:
      TABLE_NAME: "UserCommunityOwnershipRelation"
      FK_NAME_1: "UserId"
      FK_NAME_2: "CommunityId"
