service: ${env:API_NAME}-community-collection

custom:
  dotenv:
    path: ../../../.env

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  region: ${env:REGION}
  runtime: nodejs12.x
  timeout: 30
  stage: ${env:NODE_ENV}
  versionFunctions: false
  vpc:
    securityGroupIds:
      - ${env:SECURITY_GROUP_ID}
    subnetIds:
      - ${env:SUBNET1_ID}
      - ${env:SUBNET2_ID}

package:
  individually: true

functions:
 communityCollectionOwnershipRelationCreate:
    handler: ../handler.ownershipRelationCreate
    events:
      - http:
          path: communityCollectionOwnershipRelations
          method: post
          cors: true
    environment:
      TABLE_NAME: "CommunityCollectionOwnershipRelation"
  communityCollectionOwnershipRelationGetOne:
    handler: ../handler.ownershipRelationGetOne
    events:
      - http:
          path: communityCollectionOwnershipRelations/{id1}/{id2}
          method: get
          cors: true
    environment:
      TABLE_NAME: "CommunityCollectionOwnershipRelation"
      FK_NAME_1: "CommunityId"
      FK_NAME_2: "CollectionId"
  communityCollectionOwnershipRelationGetAll:
    handler: ../handler.ownershipRelationGetAll
    events:
      - http:
          path: communityCollectionOwnershipRelations
          method: get
          cors: true
    environment:
      TABLE_NAME: "CommunityCollectionOwnershipRelation"
  communityCollectionOwnershipRelationUpdate:
    handler: ../handler.ownershipRelationUpdate
    events:
      - http:
          path: communityCollectionOwnershipRelations/{id1}/{id2}
          method: put
          cors: true
    environment:
      TABLE_NAME: "CommunityCollectionOwnershipRelation"
      FK_NAME_1: "CommunityId"
      FK_NAME_2: "CollectionId"
  communityCollectionOwnershipRelationDestroy:
    handler: ../handler.ownershipRelationDestroy
    events:
      - http:
          path: communityCollectionOwnershipRelations/{id1}/{id2}
          method: delete
          cors: true
    environment:
      TABLE_NAME: "CommunityCollectionOwnershipRelation"
      FK_NAME_1: "CommunityId"
      FK_NAME_2: "CollectionId"